@urlDev = http://localhost:3052/v1/api

POST {{urlDev}}/shop/logout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODRlMzA0NmNhODcxMmY3ZGU3NGQ0NDQiLCJzZXNzaW9uSWQiOiIwNjBkMjU2Zi1mMTY4LTRhMGMtYjMxOC0wOTgxNGM1NjZhMWUiLCJpYXQiOjE3NDk5NTY3MjMsImV4cCI6MTc1MDU2MTUyM30.IbzpHG0dL936Z_TThtdVxlOP-shCys-_omJkvbnO9qK7FLcdeUtTA8-RlX0DH57WOVgM1BrJXkVn7YBH2fCbj31TYLyAeQ3neT-TsYQ_MlIvoXhY4Br4ER_O4lmaO0ML3ndL8msu4G-mvVWFlv5-CkKKuAyB5dn9uOEO5gXX3ICk4vN_UlNUZhOdmRY7pgCiZxC6e3cCJ1FIPBeogyGEUJRboK0EUliXj37Yaj5LgwP3hFxIrY5xvQJ0qqwz8mKuJqzjWmmNS1yED69GwMP7eGHkZT9Y8iUTJMGwMJbxPUbrNcdMIYgZL8_WmF1DOnIIXI8Duba6VBq4-My2aBJNq1E2xA0aq7736XE1KODmBpL-6INHA_7wd5VQXu3oPgQWVLEqiQ0e-CTbwT185fk6XzlstIZsybl20BCY4srG6bhzm07ateOU4Im2jmFX0rylG9ifWYp-bU_w-ZzcCgTVhg5NFYm4Ex9X6_2iYQg250dXaodxB02nvT2cysZpKc8SqD-Q8QELOCYYOHbwnWjgkFYWikzWJ5RamvvFPB4cO4hiB5Px0yvrb4R9vUQQmDnAQ3SFWy5d-dusIyouhZorsMV3AVF4jIINPmiOIl6nehhJTr7XwlndNil4GN4k8ig3nZcxuiaxouc1tpv0o4H7i5JFWxZD4beo7Ox2nD22Nes
