@urlDev = http://localhost:3052/v1/api

POST {{urlDev}}/shop/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODRlMzA0NmNhODcxMmY3ZGU3NGQ0NDQiLCJzZXNzaW9uSWQiOiIzMzU3MDYzNC0zYjJlLTRhNjAtYWFiOC01ZmM1Y2M2Zjg5MTciLCJpYXQiOjE3NDk5NTYzODQsImV4cCI6MTc1MDU2MTE4NH0.W-RKHEWxTtJzHgLBOxa45tK0gF0sBXUhuzmXF4uFFEE0De1rfAOsMOsNBZnfnc0R6cowT2zpmVj0Tbz9AzyN6qsnYvXc9aMZaCwG0KQVwcMf-iH6-i5Lvpr7rD9DTGkKKEO5aFiX2l32havDPvQZi201O9Vff5ZjAqNAaEKa2Z8dsksJDy45Erd8yKpfabA9odMh712OCe4vfConShYz_iGiv7-Mfey_6Ub-7wvvaYnWZf7cqj8chjInYZlH18EnzNe1fMfRL6pcuSh3uwpkp_h82XxJeWzFr9hhBn9pGQJ6hm_QO0ftqqtsuDE7DN0MZ4g3qOxlwtClLvSFk8rZBnsLioPQ2oMj-I6giP-dD4_-Z7pdZbvjxn65UOcSrk7frk0vM5bNasRRzCKGnTbgH1rA6IrzIxD6Ti9OwRRV-8drpmBAboyWYjWylq-WGHp054-ibfsHDBy0J4MubQ8MUKQ0pRXgoiruSFbZ9cN8ztxerTmwq8B9rsPFbMuewv3K9p-NposQpGXc7kFTCtUADoIS1q8AH9pKtzlfiSyGpZnInXoc4wEVb-v-EppxojcPBRC-TSoLBeVAS3uGk1oLmdzH59a7-5iAHFSpV_1EoYtxZO2PEjGz0Z4B4f2WRtOk-qCpG7svbBi-2ruZvdVinXrgoLKULTZ4KRzifzNR_2Q

{
    "email": "shop01@gmail.com",
    "password": "321987"
}